name: Build and Deploy .NET App to SmarterASP

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: windows-latest 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0' 

    - name: Install EF Core Tools
      run: dotnet tool install --global dotnet-ef

    - name: Restore NuGet Packages
      run: dotnet restore
    - name: Apply Database Migrations
      run: |
        dotnet ef database update --project ./HttpLab.csproj --connection "${{ secrets.DB_CONNECTION_STRING }}"

    - name: Build and Publish Application
      run: dotnet publish ./HttpLab.csproj --configuration Release --output ./publish

    - name: Upload Files to Server via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: win9079.site4now.net       
        username: faisal0101-001             
        password: ${{ secrets.FTP_PASSWORD }} 
        local-dir: ./publish/
        server-dir: /site1/